[package]
name = "water_effect"
version = "0.1.0"
edition = "2021"

[workspace]
resolver = "2"
members = ["game"]

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[dependencies]
bevy = "0.8"
game = { path = "game" }
